### ISSUE TITLE
希望能够有java8的版本

### ISSUE THREAD

**Issue by Xnidada** [Bottle-M/PotatoPeeler#1]
希望能够有java8的版本，以支持较低版本

**Comment by SomeBottle** [comment]
感谢你的建议，现在 PotatoPeeler 已经兼容 Java 8 了，要下载 jar 包的话请前往: https://github.com/Bottle-M/PotatoPeeler/releases/tag/1.0.1  

如果这个小工具能帮助到你，希望能点个 Star ☺️

**Comment by Xnidada** [comment]
感谢感谢，效率太高了
